name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install
      
      - name: Install Angular CLI
        run: npm install -g @angular/cli

       - name: Configure Git Authentication
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git config --global credential.helper store
          echo "https://${{ secrets.GITHUB_TOKEN }}:@github.com" > ~/.git-credentials

      # Deployar a GitHub Pages
      - name: Deploy to GitHub Pages
        run: ng deploy --base-href=https://AdrianRojas4414.github.io/TecWebProyFinal/